import { ITask, TaskStatus, TaskEntity, TaskPriority } from '../../entities/task.entity';

// 3. Базовий декоратор
export abstract class TaskDecorator implements ITask {
  constructor(protected wrappee: ITask) {}

  // Тепер ми прокидаємо всі поля через геттери без жодних any!
  get id(): string { return this.wrappee.id; }
  get title(): string { return this.wrappee.title; }
  get status(): TaskStatus { return this.wrappee.status; }
  get priority(): TaskPriority { return this.wrappee.priority; }
  get userId(): string { return this.wrappee.userId; }
  get deadline(): Date | undefined { return this.wrappee.deadline; }
  get description(): string | undefined { return this.wrappee.description; }
  get subjectId(): string | undefined { return this.wrappee.subjectId; }

  completeTask(): ITask | null {
    return this.wrappee.completeTask();
  }
}

// 4. Конкретний декоратор (розширює поведінку)
export class RecurringTaskDecorator extends TaskDecorator {
  constructor(
    wrappee: ITask,
    private recurrenceDays: number
  ) {
    super(wrappee);
  }

  // Перевизначаємо метод для додаткової логіки (генерація нової таски)
  override completeTask(): ITask | null {
    // 4.1. Виконуємо стандартне закриття поточної таски
    super.completeTask();

    // 4.2. Додаткова логіка: генеруємо наступний дедлайн
    const nextDeadline = this.calculateNextDeadline(this.deadline);
    
    // 4.3. Створюємо дублікат завдання без ЖОДНИХ any!
    const newTask = new TaskEntity(
      `auto-gen-${Date.now()}`, 
      this.title,            // Використовуємо геттер
      TaskStatus.TODO,
      this.priority,         // Зберігаємо оригінальний пріоритет
      this.userId,           // Безпечно беремо через геттер
      `Autogenerated recurring task for: ${this.title}`,
      nextDeadline,
      this.subjectId         // Безпечно беремо через геттер
    );

    console.log(`[RecurringTaskDecorator] Task '${this.title}' completed. Next recurrence: ${nextDeadline}`);
    
    // Повертаємо нове завдання
    return newTask;
  }

  private calculateNextDeadline(currentDeadline?: Date): Date {
    const nextDate = currentDeadline ? new Date(currentDeadline) : new Date();
    nextDate.setDate(nextDate.getDate() + this.recurrenceDays);
    return nextDate;
  }
}
