### File: api.http
@baseUrl = http://localhost:3000

### 1. Register User
# @name register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "vladyslav@kpi.ua",
  "password": "gfhjkm_lkz_fdnjhbpfwss",
  "firstName": "Vladyslav",
  "lastName": "Student"
}

### 2. Login User
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "vladyslav@kpi.ua",
  "password": "gfhjkm_lkz_fdnjhbpfwss"
}

### Збереження токена (працює автоматично завдяки @name login)
@token = {{login.response.body.accessToken}}

### 3. Create Subject (захищено JWT)
# @name createSubject
POST {{baseUrl}}/subjects
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Clean Architecture Methods",
  "teacherName": "Robert C. Martin",
  "color": "#00FF00"
}

### Збереження Subject ID
@subjectId = {{createSubject.response.body.data.id}}

### 4. Get Subjects (захищено JWT, дістає всіх предметів поточного юзера)
GET {{baseUrl}}/subjects
Authorization: Bearer {{token}}

### 5. Create Task (захищено JWT)
# @name createTask
POST {{baseUrl}}/tasks
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Complete Smart Study Hub",
  "priority": "HIGH",
  "subjectId": "{{subjectId}}"
}

### Збереження Task ID
@taskId = {{createTask.response.body.data.id}}

### 6. Update Task Status -> DONE (Тригерить Command та Observer)
PATCH {{baseUrl}}/tasks/{{taskId}}/status
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "status": "DONE"
}