### File: api.http
@baseUrl = http://localhost:3000

### 1. Register User
# @name register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "vladyslav@kpi.ua",
  "password": "gfhjkm_lkz_fdnjhbpfwss",
  "firstName": "Vladyslav",
  "lastName": "Student"
}

### 2. Login User
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "vladyslav@kpi.ua",
  "password": "gfhjkm_lkz_fdnjhbpfwss"
}

### Збереження токена (працює автоматично завдяки @name login)
@token = {{login.response.body.accessToken}}

### 3. Create Subject (захищено JWT)
# @name createSubject
POST {{baseUrl}}/subjects
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Clean Architecture Methods",
  "teacherName": "Robert C. Martin",
  "color": "#00FF00"
}

### Збереження Subject ID
@subjectId = {{createSubject.response.body.data.id}}

### 4. Get Subjects (захищено JWT, дістає всіх предметів поточного юзера)
GET {{baseUrl}}/subjects
Authorization: Bearer {{token}}

### 5. Create Task (захищено JWT)
# @name createTask
POST {{baseUrl}}/tasks
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Complete Smart Study Hub",
  "priority": "HIGH",
  "subjectId": "{{subjectId}}"
}

### Збереження Task ID
@taskId = {{createTask.response.body.data.id}}

### 6. Update Task Status -> DONE (Тригерить Command та Observer)
PATCH {{baseUrl}}/tasks/{{taskId}}/status
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "status": "DONE"
}

### 7. Create Note Folder (Composite Container)
# @name createFolder
POST {{baseUrl}}/notes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Clean Architecture Notes",
  "subjectId": "{{subjectId}}"
}

### Збереження Folder ID
@folderId = {{createFolder.response.body.data.id}}

### 8. Create Note Item inside Folder (Composite Leaf)
POST {{baseUrl}}/notes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Chapter 1: SOLID principles",
  "content": "S - Single Responsibility Principle...",
  "parentId": "{{folderId}}",
  "subjectId": "{{subjectId}}"
}

### 9. Get Notes Tree (Перевірка патерну Composite)
GET {{baseUrl}}/notes/tree
Authorization: Bearer {{token}}

### 10. Get Sorted Tasks (Перевірка патерну Strategy)
# Зміни sort=deadline на priority або title для перевірки різних стратегій
GET {{baseUrl}}/tasks?sort=deadline
Authorization: Bearer {{token}}