import { randomUUID } from 'crypto';
import { ITask, TaskStatus, TaskEntity, TaskPriority } from '../../task.entity';

//Базова обгортка
export abstract class TaskDecorator implements ITask {
  constructor(protected wrappee: ITask) {}

  get id(): string { return this.wrappee.id; }
  get title(): string { return this.wrappee.title; }
  get status(): TaskStatus { return this.wrappee.status; }
  get priority(): TaskPriority { return this.wrappee.priority; }
  get userId(): string { return this.wrappee.userId; }
  get deadline(): Date | undefined { return this.wrappee.deadline; }
  get description(): string | undefined { return this.wrappee.description; }
  get subjectId(): string | undefined { return this.wrappee.subjectId; }

  completeTask(): ITask | null {
    return this.wrappee.completeTask();
  }
}

export class RecurringTaskDecorator extends TaskDecorator {
  constructor(
    wrappee: ITask,
    private recurrenceDays: number
  ) {
    super(wrappee);
  }

  override completeTask(): ITask | null {
    //Виконуємо базове завершення (status = DONE)
    super.completeTask();

    //Створюємо і повертаємо НОВЕ завдання
    const nextDeadline = this.calculateNextDeadline(this.deadline);
    return new TaskEntity({
      ...this.wrappee, // Копіюємо дані
      id: randomUUID(),
      status: TaskStatus.TODO,
      deadline: nextDeadline,
      description: `Autogenerated recurring task for: ${this.title}`,
    });
  }


  private calculateNextDeadline(currentDeadline?: Date): Date {
    const nextDate = currentDeadline ? new Date(currentDeadline) : new Date();
    nextDate.setDate(nextDate.getDate() + this.recurrenceDays);
    return nextDate;
  }
}
